### ISSUE TITLE
I don't have an Issue

### ISSUE THREAD

**Issue by BurnOutTrader** [npouzenc/IGMarkets#1]
I am curious what you are using this for, your own locally run trading? The reason I ask is because I have been using quantconnect / Lean open source engine. I am a fairly novice programmer and I am looking at running some IG data through lean, it doesnt look to hard using your project. I thought I would point out that a fair few people in Quantconnect community have shown interest in IG markets integration and I have seen it mentionioned that Quantconnect will contribute up to $5000 for a full broker API to their standard, it might be worth your time to take a look as many of the classes and methods you have created are a good fit to Lean engines existing classes. Oanda brokerage also uses the same API library as IG markets which might help since the Oanda brokerage class exists in Lean already.

**Comment by npouzenc** [comment]
I'll close this ticket because as you mentionned it's not an issue.
Thanks for the information, I'll take a look at the "Quantconnect API" for brokerage integration to check the actual coverage of my library.
